name: pvpheads
version: 1.0
main: com.pvpheads.Main
api-version: 1.20

commands:
  fakekill:
    description: Simulates player death
    usage: /fakekill <joueur>
  spawnpassivemob:
    description: Spawns the passive mob
    usage: /spawnpassivemob <scale> <hp> <hitbox size>
